server:
  port:  9001
spring:
  application:
    name:  cloud-invoker
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka
#用yml配置文件使用自定义负载均衡器规则MyRule和服务提供者连通类MyPing
#cloud-provider:
  #ribbon:
    #NFLoadBanlancerRuleClassName:  org.crazyit.cloud.MyRule
    #NFLoadBanlancerPingClassName:  org.crazyit.cloud.MyPing
     