spring:
  application:
    name:  first-cloud-provider
eureka:
  instance:
    hostname:  localhost
    metadata-map:
      company-name:  crazyit
  client:
    instanceInfoReplicationIntervalSeconds: 20
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/,http://localhost:8762/eureka/